-- AlterTable
ALTER TABLE "leads" ADD COLUMN     "address" TEXT,
ADD COLUMN     "age" INTEGER,
ADD COLUMN     "alternate_mobile" VARCHAR(15),
ADD COLUMN     "branch" VARCHAR(100),
ADD COLUMN     "category" VARCHAR(10),
ADD COLUMN     "course_name" VARCHAR(150),
ADD COLUMN     "date_of_birth" DATE,
ADD COLUMN     "declaration_date" DATE,
ADD COLUMN     "declaration_place" VARCHAR(100),
ADD COLUMN     "education_details" JSONB,
ADD COLUMN     "enrolment_form_no" VARCHAR(50),
ADD COLUMN     "father_name" VARCHAR(100),
ADD COLUMN     "father_occupation" VARCHAR(100),
ADD COLUMN     "gender" VARCHAR(10),
ADD COLUMN     "languages_known" JSONB,
ADD COLUMN     "message_consent" BOOLEAN,
ADD COLUMN     "photo_url" TEXT,
ADD COLUMN     "pin_code" VARCHAR(10),
ADD COLUMN     "reference_friends" JSONB,
ADD COLUMN     "state" VARCHAR(50),
ADD COLUMN     "timing" VARCHAR(50),
ADD COLUMN     "work_experience" JSONB;
